### ISSUE TITLE
Final items to get on the upstream awesome list

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#35]
Please review the following comments (sindresorhus is the maintainer of the awesome project):

![image](https://cloud.githubusercontent.com/assets/1715206/25317517/30432b4e-2848-11e7-9af8-e6b69b9a090c.png)

1) Change the repo description to "Curated list of awesome open source healthcare software, libraries, tools and resources."

2) Change the repo name to `awesome-healthcare`. I believe the old links will redirect correctly as I've renamed a repo in the past without issue.

Thanks,
Matthew

**Comment by MatthewVita** [comment]
We're _so_ close to getting on the master list!

**Comment by ppazos** [comment]
Shouldn't it be "eHealth"? Since this list is about IT tools / systems / platforms for ehealth, not things for health or health care specifically.

**Comment by MatthewVita** [comment]
Hi @ppazos,

I suppose one can argue that a few of the imaging software projects aren't 100% related to health/healthcare/medical use cases. However, everything else is.

"eHealth" is not a term I hear a lot... typically it's "Health Information Technology" (HIT). The US government defines this term as "[...] a broad concept that encompasses an array of technologies to store, share, and analyze health information." [0] and includes the term in legislation [1]. It appears that this definition is in line with the software packages listed in this repository.

Objectively, `awesome-healthit`, `awesome-health-it`, or `awesome-health-information-technology` make the most sense.

Subjectively, I think `awesome-healthcare` gets the point across to those familiar with the `awesome-*` repositories. For instance, there is a repository called `awesome-transit` [2]. It is entirely technology based and doesn't have `-it` or `-technology` in the name.

I'm interested in your thoughts and of course am anxiously waiting @kakoni's reply (he is the lead maintainer).

[0] https://www.healthit.gov/patients-families/basics-health-it
[1] https://www.hhs.gov/hipaa/for-professionals/special-topics/HITECH-act-enforcement-interim-final-rule/
[2] https://github.com/luqmaan/awesome-transit

**Comment by ppazos** [comment]
@MatthewVita ehealth is a very common term and is my domain of expertise.

If you google it, you will get on the first page websites from international / national / regional bodies in charge of the health IT strategies. Even WHO and Wikipedia links.

http://www.who.int/ehealth/en/
https://en.wikipedia.org/wiki/EHealth

Also ehealth is broadly used in social networks.

HIT is focused on technology, eHealth is a broader term, includes standards, platforms, methodologies, processes, etc.

With that being said, I don't dislike HIT, but is more specific. 

On the other hand, healthcare is way more broader term and HIT is a very small piece in the healthcare domain. If I was a general user, I wouldn't understand what is currently listed in under awesome-health or awesome-healthcare. I get it because I work in the domain and most of the things listed here are familiar to me (EHRServer, openEHR, HL7, DICOM, ...).

Those are my 2 cents :D

**Comment by kakoni** [comment]
> Subjectively, I think awesome-healthcare gets the point across to those familiar with the awesome-* repositories. For instance, there is a repository called awesome-transit [2]. It is entirely technology based and doesn't have -it or -technology in the name.

My thoughts exactly. Following the common theme here makes sense. I'll change the name and desc.

**Comment by MatthewVita** [comment]
@ppazos I do see your point, but only time will tell if the right decision was made (e.g.: if our star count doesn't increase over time or people submit issues about the naming). Should this happen, I am more than happy to admit fault and adjust course accordingly.

@kakoni Thanks for making the decision quickly. I'll inform the upstream repo and hopefully, he'll check us in!

**Comment by MatthewVita** [comment]
@kakoni BTW, this got checked in :)
