### ISSUE TITLE
HIPAA Compliance Policies

### ISSUE THREAD

**Issue by notdone-au** [kakoni/awesome-healthcare#65]
[HIPAA Compliance Policies](https://github.com/catalyzeio/policies) - Makes compliance as easy as possible for companies working with protected health information.

Isn't an active link any idea where this might have gone?

**Comment by MatthewVita** [comment]
Hi @itsmejoshua,

Good find. I dug up the following:

1) A "somewhat recent" capture of the repo on archive.org here: https://web.archive.org/web/20201112015159/https://github.com/catalyzeio/policies

2) What appears to be the content hosting on a gh site: http://catalyzeio.github.io/policies/

I'm too busy due to a life situation to help much at this time, but I guess that this project has stopped (a shame). I don't want to say anything for certain because I've done virtually no research.

Interested in others' opinions!

**Comment by kakoni** [comment]
@itsmejoshua @MatthewVita I've contacted Datica (Formerly Catalyze) about this. 
I'll keep this ticket open and update on progress.

**Comment by kakoni** [comment]
Havent heard anything from Datica, so closing this for now.
